### ISSUE TITLE
Unable to build demo

### ISSUE THREAD

**Issue by hxdnshx** [adamrehn/ue4-cloud-rendering-demo#1]
I executed `./run-demo-janus.sh` to run this demo, but i got following error in step `RUN cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .`:

> CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCCompiler.cmake:48 (message):
>  Could not find compiler set in environment variable CC:
>
>  clang-5.0.
>Call Stack (most recent call first):
>  CMakeLists.txt:2 (project)
>
>
>CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
>CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
>-- Configuring incomplete, errors occurred!
>See also "/tmp/MediaIPC/build/CMakeFiles/CMakeOutput.log".

To solve this error, i modified `./project/Dockerfile`,and then everything works right:

>...
>#Build the MediaIPC example consumers
>ENV CC=clang-5.0
>ENV CXX=clang++-5.0
>RUN git clone --progress --depth=1 https://github.com/adamrehn/MediaIPC.git /tmp/MediaIPC
>WORKDIR /tmp/MediaIPC/
>RUN conan install .
>RUN mkdir /tmp/MediaIPC/build
>WORKDIR /tmp/MediaIPC/build
>#New Code
>USER root
>RUN apt-get install -y --no-install-recommends clang-5.0
>USER ue4
>#New Code
>RUN cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .
>...

I'm not sure which script caused the missing of clang-5.0...

**Comment by adamrehn** [comment]
Oops, that configuration is from back when the Docker images unconditionally installed clang 5.0, rather than using the appropriate clang according to the installed version of the Unreal Engine. I've updated the Dockerfile in commit 92cce0c to reflect the current state of the Docker images. Could you please retry the build with the latest Dockerfile and let me know how if everything works for you?

**Comment by hxdnshx** [comment]
Thanks for your consideration. Now that works, ./project/Dockerfile is able to build without any error.
