### ISSUE TITLE
Unable to build due to conan profile not existing?

### ISSUE THREAD

**Issue by amesgames** [adamrehn/ue4-cloud-rendering-demo#3]
Out of the box, I get this error when building through the janus script:

<pre>
Step 7/13 : RUN 	export CC=`conan profile get env.CC ue4` && 	export CXX=`conan profile get env.CXX ue4` && 	conan install . && 	mkdir /tmp/MediaIPC/build && 	cd /tmp/MediaIPC/build && 	cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .
 ---> Running in d7bba8a9ca4f
ERROR: Key not found: 'env.CC'
ERROR: Key not found: 'env.CXX'
</pre>

Then later:

<pre>boost/1.67.0@conan/stable: WARN: Lib folder doesn't exist, can't collect libraries: /home/ue4/.conan/data/boost/1.67.0/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib</pre>

Then:

<pre>
CMake Error at conanbuildinfo.cmake:644 (message):
  Incorrect 'clang', is not the one detected by CMake: 'GNU'
Call Stack (most recent call first):
  conanbuildinfo.cmake:227 (conan_check_compiler)
  CMakeLists.txt:19 (conan_basic_setup)
</pre>

This is on Ubuntu 18.04. I believe I have installed all the correct dependencies.

**Comment by adamrehn** [comment]
I've fixed this so that it builds successfully with the latest changes in how conan-ue4cli handles profile generation, but I'd still strongly recommend using [Pixel Streaming for Linux](https://adamrehn.com/articles/pixel-streaming-in-linux-containers/) rather than the old UE4Capture plugin that this demo is built around.
