### ISSUE TITLE
HELP！failed to run ./run-demo-janus.sh

### ISSUE THREAD

**Issue by CFHH** [adamrehn/ue4-cloud-rendering-demo#4]
boost/1.67.0@conan/stable: WARN: Lib folder doesn't exist, can't collect libraries: /home/ue4/.conan/data/boost/1.67.0/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib
./build.sh: 9: export: /tmp/MediaIPC/build: bad variable name
ERROR: Service 'demo' failed to build : The command '/bin/sh -c conan install . --profile ue4 && 	conan install . --profile ue4 -g=virtualenv && 	cat activate.sh >> build.sh && 	echo 'mkdir /tmp/MediaIPC/build && cd /tmp/MediaIPC/build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .' >> build.sh && 	chmod +x build.sh && 	./build.sh' returned a non-zero code: 2

**Comment by CFHH** [comment]
I have edited the dockerfile and manually installed boost1.67, then all the 3 containers were built successfully.
BUT, I have a new problem that I couldn't see the image via http://127.0.0.1:8000/. 
webrtc_1     | [WARN] [5137486376439308] Received IPv6 candidate, but IPv6 support is disabled...
webrtc_1     | [ERR] [ice.c:janus_ice_trickle_parse:639] [5137486376439308] Failed to parse candidate... (5)
webrtc_1     | [WARN] [5137486376439308] Received IPv6 candidate, but IPv6 support is disabled...
webrtc_1     | [ERR] [ice.c:janus_ice_trickle_parse:639] [5137486376439308] Failed to parse candidate... (5)

What should I do?

**Comment by adamrehn** [comment]
This repository is quite outdated at this point, and I'm now strongly recommending that people use [Pixel Streaming for Linux](https://adamrehn.com/articles/pixel-streaming-in-linux-containers/) rather than the old UE4Capture plugin that this demo is built around. I might look into getting a more recent version of Janus working with Pixel Streaming at some point in the future, but unfortunately I'm not actively providing support for the old demo as it currently exists.
